# Numpy

In [1]:
# das Modul importieren
import numpy as np # "np" hat sich etabliert

## Numpy Arrays

In [7]:
# Wiederholung: Python
[1, 2, 3, 4] # list
(1, 2, 3, 4) # tuple

# Numpy Array
a = np.array([2, 3, 4, 5])
print(a)

print()

# multi-dimensional:
b = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(b)

[2 3 4 5]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Array-Operationen

In [51]:
print(a)
print(a + 1) # element-wise operation
print(a * 2)

print()

print(b)
print(b + 1) # element-wise operation
print(b * 2)

# was wir (ich) waehrend des seminars vergessen haben:
print()
print(a)
print(a > 3)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[0 1 2 3 4 5 6 7 8 9]
[False False False False  True  True  True  True  True  True]





Im Gegensatz dazu das Verhalten von Python-Listen:

In [19]:
[1, 2, 3, 4] + [1] # concatenate (listen)

[1, 2, 3, 4, 1]

### Auf Array-Elemente zugreifen

In [22]:
print(a[0])

print(b[0]) # erste (nullte) Zeile

print(b[1, 2]) # Element aus der zweiten Zeile, dritte Spalte

2
[1 2 3]
6


In [71]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
print("[1, 4)  = inklusive 1, exklusive 4 \t\t", a[1:4])
print("von 1 bis Ende \t\t\t\t\t", a[1:])
print("von Anfang bis Ende \t\t\t\t", a[:])
print("9. Element (in diesem Fall das letzte Element) \t", a[9])
print("letztes element \t\t\t\t", a[-1])
print("vorletztes element \t\t\t\t", a[-2])
print("inkl. 2 bis exkl. vorletztes: \t\t\t", a[2:-2])

print()

print("zweite und dritte Zeile:\n", b[1:3], "\n") 
print("zweite bis letzte Zeile:\n", b[1:], "\n")
print("zweite Spalte\n", b[:, 1], "\n(Elemente aus allen Zeilen, aber nur jeweils aus der zweiten Spalte)")

[0 1 2 3 4 5 6 7 8 9]
[1, 4)  = inklusive 1, exklusive 4 		 [1 2 3]
von 1 bis Ende 					 [1 2 3 4 5 6 7 8 9]
von Anfang bis Ende 				 [0 1 2 3 4 5 6 7 8 9]
9. Element (in diesem Fall das letzte Element) 	 9
letztes element 				 9
vorletztes element 				 8
inkl. 2 bis exkl. vorletztes: 			 [2 3 4 5 6 7]

zweite und dritte Zeile:
 [[4 5 6]
 [7 8 9]] 

zweite bis letzte Zeile:
 [[4 5 6]
 [7 8 9]] 

zweite Spalte
 [2 5 8] 
(Elemente aus allen Zeilen, aber nur jeweils aus der zweiten Spalte)


**Nebenbemerkung:**

'Tab' --> Autocompletion

'Shift-Tab' --> Dokumentation

## Numpy-Arrays erstellen

### np.linspace und np.arange

In [73]:
p = np.linspace(0, 20, 100)
print(p, "\n")
p = np.linspace(0, 20, 10)
print(p, "\n")
p = np.linspace(0, 20, 21)
print(p)

[ 0.          0.2020202   0.4040404   0.60606061  0.80808081  1.01010101
  1.21212121  1.41414141  1.61616162  1.81818182  2.02020202  2.22222222
  2.42424242  2.62626263  2.82828283  3.03030303  3.23232323  3.43434343
  3.63636364  3.83838384  4.04040404  4.24242424  4.44444444  4.64646465
  4.84848485  5.05050505  5.25252525  5.45454545  5.65656566  5.85858586
  6.06060606  6.26262626  6.46464646  6.66666667  6.86868687  7.07070707
  7.27272727  7.47474747  7.67676768  7.87878788  8.08080808  8.28282828
  8.48484848  8.68686869  8.88888889  9.09090909  9.29292929  9.49494949
  9.6969697   9.8989899  10.1010101  10.3030303  10.50505051 10.70707071
 10.90909091 11.11111111 11.31313131 11.51515152 11.71717172 11.91919192
 12.12121212 12.32323232 12.52525253 12.72727273 12.92929293 13.13131313
 13.33333333 13.53535354 13.73737374 13.93939394 14.14141414 14.34343434
 14.54545455 14.74747475 14.94949495 15.15151515 15.35353535 15.55555556
 15.75757576 15.95959596 16.16161616 16.36363636 16

In [74]:
print(np.arange(21))
print(np.arange(2, 21))
print(np.arange(2, 21, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


## PI

In [37]:
np.pi

3.141592653589793